owner: SwiftFiddle
repo: status.swift-format.com

sites:
  - name: swift-format.com
    url: https://swift-format.com/
  - name: swift-format.com/api
    method: POST
    url: https://swift-format.com/api
    headers:
      - "Content-Type: application/json"
    body: '{ "code":"func hello() { print(\"Hello World!!\") }\n hello()" }'

status-website:
  cname: status.swift-format.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SwiftRegex Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "*/20 * * * *"
